name: Build Linux Container Image and Push to ACR

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    
    - uses: azure/docker-login@v1
      with:
        login-server: newtestdemo.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t newtestdemo.azurecr.io/myapp1:latest
        docker push newtestdemo.azurecr.io/myapp1:latest