name: Build Linux Container Image and Push to ACR

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    
    - uses: azure/docker-login@v1
      with:
        login-server: alloan.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t alloan.azurecr.io/AlloanAutoContainer:Image-latest.
        docker push alloan.azurecr.io/AlloanAutoContainer:Image-${{ steps.date.outputs.date }}.