name: Build Custom Container Image and Deploy  

on:
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current image version
        id: get_version
        run: |
          echo "IMAGE_VERSION=$((${{ secrets.IMAGE_VERSION }} + 1))" >> $GITHUB_ENV

      - name: Update Git secret
        run: |
          echo "IMAGE_VERSION=${{ steps.get_version.outputs.version }}" >> $GITHUB_ENV
          echo "Setting new image version: $IMAGE_VERSION"
          echo -n $IMAGE_VERSION | base64 --decode | git secrets --add

      - name: Build and push Docker image
        env:
          IMAGE_VERSION: ${{ steps.get_version.outputs.version }}
        run: |
          docker build -t my-docker-image:$IMAGE_VERSION .
          docker tag my-docker-image:$IMAGE_VERSION myacr.azurecr.io/my-docker-image:$IMAGE_VERSION
          docker login myacr.azurecr.io -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
          docker push myacr.azurecr.io/my-docker-image:$IMAGE_VERSION
          
