name: Build Linux Container Image and Push to ACR

on:
  pull_request:
    types:
      - closed:


jobs:
  merge-job:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    
    - uses: azure/docker-login@v1
      with:
        login-server: alloan.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t alloan.azurecr.io/alloan_auto_container: Image_version_01
        docker push alloan.azurecr.io/alloan_auto_container:Image_version_01